### ISSUE TITLE
Add others Minigame

### ISSUE THREAD

**Issue by BlackRam-oss** [methanoliver/awesome-renpy#2]
- https://www.renpy.org/wiki/renpy/frameworks/SoftKeyboard
- https://www.renpy.org/wiki/renpy/Cardgame

**Comment by methanoliver** [comment]
Pretty sure cardgame is listed already - and, did you actually test the SoftKeyboard? Is there even a point using either these days, when the expectation is these things are to be done using screens instead?

**Comment by BlackRam-oss** [comment]
yes you are right I had not seen it.

for the keyboard on second thought it doesn't make much sense.

**Comment by methanoliver** [comment]
I'll be closing this for now, then, until someone makes a new one. :)
