### ISSUE TITLE
RPA Explorer description correction

### ISSUE THREAD

**Issue by UniverseDevel** [methanoliver/awesome-renpy#4]
Hi,

thank you for including RPA Explorer to this awesome list. I just need to point out that description to this item might be a little missleading.

> [RPA Explorer](https://github.com/UniverseDevel/RPA-Explorer) - Essentially a GUI for `unrpa`.

Few information that might help you describe the tool better:

1. It is not GUI for anything, as it is standalone C# RPA (un)packer library with GUI attached to it, your description kinda leads me to think `unrpa` is maybe even needed for it to work or something.
2. `unrpa` is actually not involved at all. I did not even know it existed at the moment when I wrote this app. C# RPA (un)packer library was actaully inspired by `rpatools` code and GUI was supposed to bring some ease of use and live preview.
3. There is also functionality to preview encoded rpyc files and for that `unrpyc` is needed with Python 2.7 installed, but this is optional and all the other features work without this script except encoded rpyc files preview.
4. C# RPA (un)packer library can be used on its own without the GUI. If somone needs a programatical way how to work with RPA archive in their C# project, they can add this library without the need for GUI code, to readuce the size of this tool significantly.

In case you feel that it is still sufficent description I would at least add correct tool (`rpatools` https://github.com/Shizmob/rpatool) instead of `unrpa` just so credit is pointed the proper way.

Anyway have a nice day and thanks. ;)

**Comment by methanoliver** [comment]
You could have just sent in a PR with your corrections instead of writing this. :)

Gimme a moment...
